#!/bin/sh

### BEGIN INIT INFO
# Provides: aesdsocket
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs &syslog
# Default-Start: 2 3 4 5
# Defaulttt-Stop: 0 1 6
# Short-Description: Start/stop aesdsocket daemon
### END INIT INFO

DAEMON=/usr/bin/aesdsocket
DAEMON_OPTS="-d"
NAME=aesdsocket
PIDFILE=/var/run/$NAME.pid

case "$1" in
	start)
		echo "Starting $NAME..."
		start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
		;;
	stop)
		echo "Stopping $NAME..."
		start-stop-daemon --stop --pidfile $PIDFILE --retry 10
		;;
	restart)
		echo "Restarting $NAME..."
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
